package org.Exception;

import java.util.Scanner;

public class Demo_One {
	
	
	public static void main(String[] args) {
//		Arithmetic 
		
//		System.out.println(10);
//		System.out.println(20);
//		System.out.println(40);
//		
//		try {
//			System.out.println(30/4);
//			
//		} catch (ArithmeticException e) {
//			System.out.println("handle the exception");
//		}	
		
//		InputMismatch
		
		Scanner sc = new Scanner(System.in);
		System.out.println("what is your age");
		int a = sc.nextInt();
		System.out.println(a*a);
		
		
		
		
		
		
	}
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	

}
